version: "3"
services:
  db:
    image: postgres
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=testdemo
      - PGDATA=tmp
    #networks:
    #  - app-network
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      #- ./postgresql/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
  app:
    build: .
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/testdemo
    volumes:
      - ./:/usr/src/app
    command:
      - --reload
    depends_on:
      db:
        condition: service_healthy
